// <auto-generated />
using System;
using Exer4_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exer4_2.Migrations
{
    [DbContext(typeof(Ex4DbContext))]
    [Migration("20250502151938_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exer4_2.Models.Agent", b =>
                {
                    b.Property<int>("AgentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentID"));

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AgentName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AgentID");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            AgentID = 1,
                            Address = "10 Pine St",
                            AgentName = "Alice Smith"
                        },
                        new
                        {
                            AgentID = 2,
                            Address = "22 Oak Ave",
                            AgentName = "Bob Johnson"
                        },
                        new
                        {
                            AgentID = 3,
                            Address = "33 Elm Rd",
                            AgentName = "Charlie Brown"
                        },
                        new
                        {
                            AgentID = 4,
                            Address = "44 Willow Ln",
                            AgentName = "Diana Lee"
                        },
                        new
                        {
                            AgentID = 5,
                            Address = "55 Maple Dr",
                            AgentName = "Ethan Davis"
                        },
                        new
                        {
                            AgentID = 6,
                            Address = "66 Birch Ct",
                            AgentName = "Fiona Wilson"
                        },
                        new
                        {
                            AgentID = 7,
                            Address = "77 Cedar Blvd",
                            AgentName = "George Moore"
                        },
                        new
                        {
                            AgentID = 8,
                            Address = "88 Spruce Way",
                            AgentName = "Hannah Taylor"
                        },
                        new
                        {
                            AgentID = 9,
                            Address = "99 Redwood Pl",
                            AgentName = "Ian Clark"
                        },
                        new
                        {
                            AgentID = 10,
                            Address = "101 Oak St",
                            AgentName = "Julia Lewis"
                        },
                        new
                        {
                            AgentID = 11,
                            Address = "112 Pine Ave",
                            AgentName = "Kevin Hall"
                        },
                        new
                        {
                            AgentID = 12,
                            Address = "123 Elm Rd",
                            AgentName = "Linda Allen"
                        },
                        new
                        {
                            AgentID = 13,
                            Address = "134 Willow Ln",
                            AgentName = "Michael Young"
                        },
                        new
                        {
                            AgentID = 14,
                            Address = "145 Maple Dr",
                            AgentName = "Nancy King"
                        },
                        new
                        {
                            AgentID = 15,
                            Address = "156 Birch Ct",
                            AgentName = "Oliver Wright"
                        });
                });

            modelBuilder.Entity("Exer4_2.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1,
                            ItemName = "T-Shirt",
                            Size = "M",
                            Stock = 50
                        },
                        new
                        {
                            ItemID = 2,
                            ItemName = "Jeans",
                            Size = "32",
                            Stock = 30
                        },
                        new
                        {
                            ItemID = 3,
                            ItemName = "Mug",
                            Stock = 100
                        },
                        new
                        {
                            ItemID = 4,
                            ItemName = "Book",
                            Stock = 75
                        },
                        new
                        {
                            ItemID = 5,
                            ItemName = "Pen",
                            Stock = 200
                        },
                        new
                        {
                            ItemID = 6,
                            ItemName = "Sweater",
                            Size = "S",
                            Stock = 25
                        },
                        new
                        {
                            ItemID = 7,
                            ItemName = "Belt",
                            Size = "34",
                            Stock = 40
                        },
                        new
                        {
                            ItemID = 8,
                            ItemName = "Backpack",
                            Stock = 60
                        },
                        new
                        {
                            ItemID = 9,
                            ItemName = "Dress",
                            Size = "8",
                            Stock = 35
                        },
                        new
                        {
                            ItemID = 10,
                            ItemName = "Notebook",
                            Stock = 120
                        },
                        new
                        {
                            ItemID = 11,
                            ItemName = "Gloves",
                            Size = "M",
                            Stock = 70
                        },
                        new
                        {
                            ItemID = 12,
                            ItemName = "Scarf",
                            Size = "One Size",
                            Stock = 55
                        },
                        new
                        {
                            ItemID = 13,
                            ItemName = "Water Bottle",
                            Stock = 90
                        },
                        new
                        {
                            ItemID = 14,
                            ItemName = "Pants",
                            Size = "30",
                            Stock = 32
                        },
                        new
                        {
                            ItemID = 15,
                            ItemName = "Keyboard",
                            Stock = 45
                        });
                });

            modelBuilder.Entity("Exer4_2.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("AgentID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.HasKey("OrderID");

                    b.HasIndex("AgentID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderID = 1,
                            AgentID = 8,
                            OrderDate = new DateTime(2024, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 2,
                            AgentID = 8,
                            OrderDate = new DateTime(2024, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 3,
                            AgentID = 8,
                            OrderDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 4,
                            AgentID = 8,
                            OrderDate = new DateTime(2024, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            OrderID = 5,
                            AgentID = 8,
                            OrderDate = new DateTime(2024, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Exer4_2.Models.OrderDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("UnitAmount")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ItemID");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ItemID = 1,
                            OrderID = 1,
                            Quantity = 1,
                            UnitAmount = 10
                        },
                        new
                        {
                            ID = 2,
                            ItemID = 2,
                            OrderID = 1,
                            Quantity = 2,
                            UnitAmount = 20
                        },
                        new
                        {
                            ID = 3,
                            ItemID = 3,
                            OrderID = 2,
                            Quantity = 1,
                            UnitAmount = 30
                        },
                        new
                        {
                            ID = 4,
                            ItemID = 4,
                            OrderID = 2,
                            Quantity = 3,
                            UnitAmount = 15
                        },
                        new
                        {
                            ID = 5,
                            ItemID = 5,
                            OrderID = 3,
                            Quantity = 1,
                            UnitAmount = 25
                        },
                        new
                        {
                            ID = 6,
                            ItemID = 6,
                            OrderID = 3,
                            Quantity = 2,
                            UnitAmount = 35
                        },
                        new
                        {
                            ID = 7,
                            ItemID = 7,
                            OrderID = 4,
                            Quantity = 1,
                            UnitAmount = 45
                        },
                        new
                        {
                            ID = 8,
                            ItemID = 8,
                            OrderID = 4,
                            Quantity = 4,
                            UnitAmount = 12
                        },
                        new
                        {
                            ID = 9,
                            ItemID = 9,
                            OrderID = 5,
                            Quantity = 1,
                            UnitAmount = 22
                        },
                        new
                        {
                            ID = 10,
                            ItemID = 10,
                            OrderID = 5,
                            Quantity = 2,
                            UnitAmount = 32
                        },
                        new
                        {
                            ID = 11,
                            ItemID = 11,
                            OrderID = 1,
                            Quantity = 1,
                            UnitAmount = 42
                        },
                        new
                        {
                            ID = 12,
                            ItemID = 12,
                            OrderID = 2,
                            Quantity = 3,
                            UnitAmount = 18
                        },
                        new
                        {
                            ID = 13,
                            ItemID = 13,
                            OrderID = 3,
                            Quantity = 1,
                            UnitAmount = 28
                        },
                        new
                        {
                            ID = 14,
                            ItemID = 14,
                            OrderID = 4,
                            Quantity = 2,
                            UnitAmount = 38
                        },
                        new
                        {
                            ID = 15,
                            ItemID = 15,
                            OrderID = 5,
                            Quantity = 1,
                            UnitAmount = 48
                        });
                });

            modelBuilder.Entity("Exer4_2.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "alice@example.com",
                            Password = "P@$$wOrd1",
                            Username = "alice123"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "bob@example.org",
                            Password = "SecurePwd2!",
                            Username = "bob_the_builder"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "charlie@test.net",
                            Password = "MySecret3#",
                            Username = "charlie77"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "diana@sample.com",
                            Password = "StrongPass4$",
                            Username = "diana.lee"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "ethan@code.com",
                            Password = "CodeMaster5%",
                            Username = "ethan_dev"
                        },
                        new
                        {
                            UserID = 6,
                            Email = "fiona@art.net",
                            Password = "ArtLover6^",
                            Username = "fiona_art"
                        },
                        new
                        {
                            UserID = 7,
                            Email = "george@science.org",
                            Password = "Science7&",
                            Username = "george_sci"
                        },
                        new
                        {
                            UserID = 8,
                            Email = "hannah@books.com",
                            Password = "BookWorm8*",
                            Username = "hannah_read"
                        },
                        new
                        {
                            UserID = 9,
                            Email = "ian@games.net",
                            Password = "LevelUp9(",
                            Username = "ian_gamer"
                        },
                        new
                        {
                            UserID = 10,
                            Email = "julia@travel.org",
                            Password = "WorldTrip10)",
                            Username = "julia_travel"
                        },
                        new
                        {
                            UserID = 11,
                            Email = "kevin@music.com",
                            Password = "TuneTime11!",
                            Username = "kevin_music"
                        },
                        new
                        {
                            UserID = 12,
                            Email = "linda@bake.net",
                            Password = "SweetTreat12#",
                            Username = "linda_bake"
                        },
                        new
                        {
                            UserID = 13,
                            Email = "michael@photo.org",
                            Password = "SnapShot13$",
                            Username = "michael_photo"
                        },
                        new
                        {
                            UserID = 14,
                            Email = "nancy@garden.com",
                            Password = "GreenThumb14%",
                            Username = "nancy_garden"
                        },
                        new
                        {
                            UserID = 15,
                            Email = "oliver@tech.net",
                            Password = "FutureIsNow15^",
                            Username = "oliver_tech"
                        });
                });

            modelBuilder.Entity("Exer4_2.Models.Order", b =>
                {
                    b.HasOne("Exer4_2.Models.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Exer4_2.Models.OrderDetail", b =>
                {
                    b.HasOne("Exer4_2.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Exer4_2.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Exer4_2.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
